<?php

// SPDX-FileCopyrightText: 2026 Research Industrial Systems Engineering (RISE) Forschungs-, Entwicklungs- und Großprojektberatung GmbH
// SPDX-FileCopyrightText: 2018 Icinga GmbH <https://icinga.com> X.509 Module
// SPDX-License-Identifier: GPL-3.0-or-later

/* generated by icingaweb2-module-scaffoldbuilder | GPLv2+ */

namespace Icinga\Module\Selenium\Controllers;

use Icinga\Application\Config;
use Icinga\Module\Selenium\Forms\BackendConfigForm;
use ipl\Web\Compat\CompatController;

class DatabaseController extends CompatController
{
    public function init()
    {
        $this->assertPermission('config/selenium');

        parent::init();
    }


    public function backendAction()
    {
        $form = (new BackendConfigForm())
            ->setIniConfig(Config::module('selenium'));

        $form->handleRequest();

        $this->view->tabs = $this->Module()->getConfigTabs()->activate('backend');
        $this->view->form = $form;
    }
}
