<?php

// SPDX-FileCopyrightText: 2026 Research Industrial Systems Engineering (RISE) Forschungs-, Entwicklungs- und Großprojektberatung GmbH
// SPDX-FileCopyrightText: 2018 Icinga GmbH <https://icinga.com> X.509 Module
// SPDX-License-Identifier: GPL-3.0-or-later

/* generated by icingaweb2-module-scaffoldbuilder | GPLv2+ */

namespace Icinga\Module\Selenium\Controllers;


use Icinga\Application\Config;
use Icinga\Web\Controller;
use Icinga\Module\Selenium\Forms\ModuleconfigForm;

class ModuleconfigController extends Controller
{



    public function init()
    {
        $this->assertPermission('config/selenium');
        parent::init();
    }


    public function indexAction()
    {
        $form = (new ModuleconfigForm())
            ->setIniConfig(Config::module('selenium', "config"));

        $form->handleRequest();

        $this->view->tabs = $this->Module()->getConfigTabs()->activate('config/moduleconfig');
        $this->view->form = $form;
    }


    public function createTabs()
    {
        $tabs = $this->getTabs();

        $tabs->add('selenium/config', [
            'label' => $this->translate('Configure Selenium'),
            'url' => 'selenium/config'
        ]);

        return $tabs;

    }

}