<?php

/* originally from Icinga Web 2 X.509 Module | (c) 2018 Icinga GmbH | GPLv2 */
/* generated by icingaweb2-module-scaffoldbuilder | GPLv2+ */

namespace Icinga\Module\Selenium\Controllers;


use Icinga\Exception\Http\HttpException;
use Icinga\Exception\NotFoundError;

use Icinga\Module\Selenium\ProjectRestrictor;
use Icinga\Module\Selenium\Controller;
use Icinga\Module\Selenium\Forms\ProjectForm;
use Icinga\Module\Selenium\Model\Project;
use Icinga\Web\Notification;
use ipl\Html\Form;
use Icinga\Module\Selenium\Common\Database;

use ipl\Stdlib\Filter;
use ipl\Web\Url;


class ProjectController extends Controller
{
    /** @var Project The Project object */
    protected $project;
    protected $db;

    public function init()
    {
        if(!$this->Auth()->hasPermission("selenium/project/modify")){
            throw new HttpException(401,"Not allowed!");
        }
        $this->db=Database::get();

    }

    public function newAction()
    {

        $this->setTitle($this->translate('New Project'));

        $values = [];

        $form = (ProjectForm::fromId(null))->setDb($this->db)
            ->setAction((string) Url::fromRequest())->setRenderCreateAndShowButton(false)
            ->populate($values)
            ->on(ProjectForm::ON_SUCCESS, function (ProjectForm $form) {
                $pressedButton = $form->getPressedSubmitElement();
                if ($pressedButton && $pressedButton->getName() === 'remove') {
                    Notification::success($this->translate('Removed Project successfully'));


                    $this->closeModalAndRefreshRemainingViews(
                        Url::fromPath('selenium/projects')
                    );
                } else {
                    Notification::success($this->translate('Updated Project successfully'));

                    $this->closeModalAndRefreshRemainingViews(
                        Url::fromPath('selenium/projects')
                    );
                }
            })
            ->handleRequest($this->getServerRequest());

        $this->addContent($form);

    }

    public function editAction()
    {

        $this->setTitle($this->translate('Edit Project'));

        $id = $this->params->getRequired('id');

        $query = Project::on($this->db)->with([

        ]);
        $query->filter(Filter::equal('id', $id));

        $restrictor = new ProjectRestrictor();
        $restrictor->applyRestrictions($query);

        $project = $query->first();
        if ($project === null) {
            throw new NotFoundError(t('Entry not found'));
        }

        $this->project = $project;




        $values = $this->project->getValues();




        $form = (ProjectForm::fromId($id))->setDb($this->db)
            ->setAction((string) Url::fromRequest())->setRenderCreateAndShowButton(false)
            ->populate($values)
            ->on(ProjectForm::ON_SUCCESS, function (ProjectForm $form) {
                $pressedButton = $form->getPressedSubmitElement();
                if ($pressedButton && $pressedButton->getName() === 'remove') {
                    Notification::success($this->translate('Removed Project successfully'));


                    $this->closeModalAndRefreshRemainingViews(
                        Url::fromPath('selenium/projects')
                    );
                } else {
                    Notification::success($this->translate('Updated Project successfully'));

                    $this->closeModalAndRefreshRemainingViews(
                        Url::fromPath('selenium/projects')
                    );
                }
            })
            ->handleRequest($this->getServerRequest());

        $this->addContent($form);

    }

    protected function redirectForm(Form $form, $url)
    {
        if (
            $form->hasBeenSubmitted()
            && ((isset($form->valid) && $form->valid === true)
                || $form->isValid())
        ) {
            $this->redirectNow($url);
        }
    }
}
