<div class="controls">
    <?= /** @var \Icinga\Web\Widget\Tabs $tabs */
    $tabs ?>
</div>
<?php /** @var \Icinga\Web\View $this */

?>
<script>
function doSomething(){
    var encodedStringBtoA = btoa(editor.getValue());
    fetch('<?php echo $sendUrl; ?>', {
        method: 'POST',
        headers: {
            'Accept': 'application/json',
            'Content-Type': 'application/json'
        },
        body: JSON.stringify({ "file": '<?php echo $filename; ?>', "content":encodedStringBtoA, 'folder': '<?php echo $folder; ?>'})
    })
        .then(response => response.json())
        .then(response => {
            try {
                if(response['success']){
                    editor.setValue(response['content'])
                }else{
                    alert("try again...");
                } // Try to parse the response as JSON
                // The response was a JSON object
                // Do your JSON handling here
            } catch(err) {
                // The response wasn't a JSON object
                // Do your text handling here
            }
        })
        .then(response => console.log(JSON.stringify(response)))

}
</script>

<style type="text/css" media="screen">
    #editor {
        width: 100%;
        height: 90%;

    }
</style>
<div class="content">

    <h2><?= $this->translate('File')." - ".$filename ?></h2>
    <form id="IcingaFormsSaveFile" name="IcingaFormsSaveFileForm" class="icinga-form icinga-controls" onsubmit="return doSomething();">

            <input type="submit" name="btn_submit" id="IcingaFormsSaveFile-submit" value="Save" class="btn-primary">
    </form>

    <?php

    $data = htmlspecialchars(file_get_contents($filePath));

    // Format the image SRC:  data:{mime};base64,{data};
    //echo "<pre>$data</pre>";

    ?>

    <div id="editor"><?php echo $data;?></div>
    <script src=<?php echo $jsUrl; ?> ></script>

    <script>
            var editor = ace.edit("editor");
            editor.setTheme("ace/theme/monokai");
            folder='<?php echo $folder ?>';
            if( folder == "mibs" ){
                editor.session.setMode("ace/mode/yaml");
            }else if(folder == "generated_files" ){
                editor.session.setMode("ace/mode/yaml");
            }





    </script>
</div>