<?php

/* originally from Icinga Web 2 X.509 Module | (c) 2018 Icinga GmbH | GPLv2 */
/* generated by icingaweb2-module-scaffoldbuilder | GPLv2+ */

namespace Icinga\Module\Selenium\Forms;

use Icinga\Data\ResourceFactory;
use Icinga\Forms\ConfigForm;

class BackendConfigForm extends ConfigForm
{
    public function init()
    {
        $this->setName('selenium_config');
        $this->setSubmitLabel($this->translate('Save Changes'));
    }

    public function createElements(array $formData)
    {
        $dbResources = ResourceFactory::getResourceConfigs('db')->keys();

        $this->addElement('select', 'backend_resource', [
            'label'         => $this->translate('Database'),
            'description'   => $this->translate('Database resource'),
            'multiOptions'  => array_combine($dbResources, $dbResources),
            'required'      => true
        ]);
        $this->addElement('select', 'backend_object', [
            'label'         => $this->translate('Objectsbackend'),
            'description'   => $this->translate('Backend for objects'),
            'multiOptions'  => ['icingadb'=>'IcingaDb','monitoring'=>'IDO/Monitoring'],
            'required'      => true
        ]);
    }
}
