<?php

/* originally from Icinga Web 2 X.509 Module | (c) 2018 Icinga GmbH | GPLv2 */
/* generated by icingaweb2-module-scaffoldbuilder | GPLv2+ */

namespace Icinga\Module\Selenium\Forms;

use Icinga\Data\ResourceFactory;
use Icinga\Forms\ConfigForm;
use Icinga\Module\Director\Objects\DirectorDatafieldCategory;
use ipl\Stdlib\Data;

class DirectorConfigForm extends ConfigForm
{
    protected $db;
    public function init()
    {
        $this->setName('selenium_director');
        $this->setSubmitLabel($this->translate('Save Changes'));
    }
    public function setDb($db)
    {
        $this->db = $db;
        return $this;
    }

    public function createElements(array $formData)
    {

        $options =[];
        $categories = DirectorDatafieldCategory::loadAll($this->db);
        foreach ($categories as $category){
            $options[$category->get('id')]=$category->get('category_name');
        }
        $options['None']=t('Chooese a Category or leave empty');
        $this->addElement('select', 'datafield_category_id', [
            'label'         => $this->translate('datafield_category'),
            'description'   => $this->translate('Category for Datafields'),
            'multiOptions'=>$options,
            'value'=>'None'
        ]);
    }

}
